### PR TITLE
Udpate haproxy marathon script

### PR DESCRIPTION
**Pull request by ernestas-poskus**
Taken from here https://github.com/mesosphere/marathon/blob/master/examples/haproxy-marathon-bridge

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
Depends on #23
Once done, 
1. Increment marathon_playbook_version in defaults to the next version, I guess that would be "0.3.3".
1. Merge
1. Tag in releases

We do this with the other repos (i.e. [here](https://github.com/AnsibleShipyard/ansible-mesos/releases), not this one. Hasn't been much love around here. Lets spread it.

**Comment by ernestas-poskus** [comment]
incremented referenced PR and this one as well but I guess will have to rebase :)

**Comment by JasonGiedymin** [comment]
Yep rebase from master after merge.

**Comment by ernestas-poskus** [comment]
@JasonGiedymin made v0.3.3 release https://github.com/AnsibleShipyard/ansible-marathon/releases/tag/v0.3.3, good to go ?

**Pull request merged**
