### PR TITLE
Enable apt pinning

### PR DESCRIPTION
**Pull request by lhoss**
### Short description:
Added optional apt pinning by setting the pin priority in `marathon_apt_pin_priority`(disabled by default)
Thx @scaronni for implementing 👍 

Same feature (PR) in the mesos-role https://github.com/AnsibleShipyard/ansible-mesos/pull/81

### CODE REVIEW

**Comment by lhoss** [comment]
@ernestas-poskus the build is fixed now (by aligning with latest fixes from the related ansible-mesos PR)
Note: This PR also contains already another fix, I just did in the mesos-role (see https://github.com/AnsibleShipyard/ansible-mesos/pull/82 )
Happy to get both merged soon 👍

**Comment by ernestas-poskus** [comment]
@lhoss good job! also please add new variables to README

**Comment by lhoss** [comment]
> also please add new variables to README

done !

**Comment by ernestas-poskus** [comment]
Awesome, thanks !

**Pull request merged**
